services:
  service-gamemaster:
    env_file: 
      - ../../.env
    platform: linux/amd64
    image: ${APP_NAME}-gamemaster-image
    container_name: ${APP_NAME}-gamemaster-container
    hostname: ${APP_NAME}-gamemaster-container
    build:
      context: ../../
      dockerfile: ./docker/gamemaster/Dockerfile
      args:
        RUST_VERSION: 1.86
        BASE_OS: slim
    volumes:
      - ../..:/app:rw
      - ../../crates:/app/crates:ro
      - ../../crates/common:/app/crates/common:rw
      - ../../crates/gamemaster:/app/crates/gamemaster:rw
      - ../../.cache:/home/appuser/.cache:rw
    environment:
      - CUDA_VISIBLE_DEVICES=all
      - HF_HOME=/home/appuser/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    command: ["docker/gamemaster/post_build.sh"]
    networks:
      - default

networks:
  default:
    external: true
    name: ${APP_NAME}-docker-network