services:
  service-adventure:
    env_file: 
      - ../../.env
    platform: linux/amd64
    image: ${APP_NAME}-adventure-image
    container_name: ${APP_NAME}-adventure-container
    hostname: ${APP_NAME}-adventure-container
    build:
      context: ../../
      dockerfile: ./docker/adventure/Dockerfile
      args:
        RUST_VERSION: 1.86
        BASE_OS: slim
    # ports: # commenté car on est pas sencé pouvoir accéder à ce service en dehors du réseau docker ${APP_NAME}-docker-network
    #   - '${SERVICE_ADVENTURE_PORT}:${SERVICE_ADVENTURE_PORT}'
    volumes:
      - ../..:/app:rw
      - ../../crates:/app/crates:ro
      - ../../crates/common:/app/crates/common:rw
      - ../../crates/adventure:/app/crates/adventure:rw
    tty: true
    command: ["docker/adventure/post_build.sh"]
    networks:
      - default

networks:
  default:
    external: true
    name: ${APP_NAME}-docker-network